CREATE TABLE carbrand(
id bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
name_carbrand CHARACTER VARYING(150) NOT NULL UNIQUE
);

CREATE TABLE carmodel(
id bigint  PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
name_carmodel CHARACTER VARYING(150) NOT NULL UNIQUE,
carbrand_id INTEGER NOT NULL,
FOREIGN KEY (carbrand_id) REFERENCES carbrand (id) 
);

CREATE TABLE color(
id bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
carbrand_id CHARACTER VARYING(50) NOT NULL,
code_color CHARACTER VARYING(150) UNIQUE NOT NULL,
name_color CHARACTER VARYING(150),
FOREIGN KEY (carbrand_id) REFERENCES carbrand(id) 
);

CREATE TABLE car(
id bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
vin CHARACTER (17) NOT NULL UNIQUE,
carband_id INTEGER NOT NULL,
carmodel_id INTEGER NOT NULL,
release_year INTEGER NOT NULL,
transmission CHARACTER VARYING(30) NOT NULL,
body_type CHARACTER VARYING(150) NOT NULL,
mileage INTEGER NOT NULL,
color_id varchar(150) NOT NULL,
country CHARACTER VARYING(150),
price INTEGER NOT NULL,
discription TEXT,
FOREIGN KEY (carmodel_id) REFERENCES carmodel(id) ,
FOREIGN KEY (carband_id) REFERENCES carbrand(id),
FOREIGN KEY (color_id) REFERENCES color(id)
); 

CREATE TABLE customer (
id  bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
first_name CHARACTER VARYING(80) NOT NULL,
last_name CHARACTER VARYING(80) NOT NULL,
phone CHARACTER VARYING(30),
address CHARACTER VARYING(260) NOT NULL,
e_mail CHARACTER VARYING(150),
age INTEGER
);

CREATE TABLE employee(
id bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
first_name CHARACTER VARYING(30) NOT NULL,
last_name CHARACTER VARYING(30) NOT NULL,
age INTEGER,
position CHARACTER VARYING(150) NOT NULL,
salery INTEGER NOT NULL
);

CREATE TABLE order(
id bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
car_id INTEGER NOT NULL,
customer_id INTEGER NOT NULL,
employee_id INTEGER NOT NULL,
date_order  TIMESTAMP NOT NULL DEFAULT now(),
status BOOLEAN DEFAULT Fales,
order_price INTEGER NOT NULL,
FOREIGN KEY (car_id) REFERENCES car(id),
FOREIGN KEY (customer_id) REFERENCES customer(id),
FOREIGN KEY (employee_id) REFERENCES  employee(id) 
);

BEGIN;
ALTER table customer ADD passport CHARACTER VARYING(150);
ALTER table customer ALTER passport SET NOT NULL;
CREATE UNIQUE INDEX passport_idx ON customer(passport);
COMMIT;

CREATE INDEX release_year_idx ON car(release_year);
